export const LEASH_ABI = [
  {
    type: "function",
    name: "getAgent",
    stateMutability: "view",
    inputs: [{ name: "agentId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "wallet", type: "address" },
          { name: "principal", type: "address" },
          { name: "mandate", type: "string" },
          { name: "mandateHash", type: "bytes32" },
          { name: "spendCap", type: "uint256" },
          { name: "expiresAt", type: "uint256" },
          { name: "deadline", type: "uint256" },
          { name: "erc7710DelegationHash", type: "bytes32" },
          { name: "delegationManager", type: "address" },
          { name: "paused", type: "bool" },
          { name: "registered", type: "bool" },
          { name: "awaitingVerdict", type: "bool" },
          { name: "nonce", type: "uint256" },
          { name: "warningCount", type: "uint256" },
          { name: "threatScore", type: "uint256" },
          { name: "approvedNextSpend", type: "uint256" },
          { name: "lastSubmissionId", type: "uint256" },
          { name: "approvedDestination", type: "address" },
          { name: "lastVerdict", type: "uint8" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "threatThreshold",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "agentCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "canProceed",
    stateMutability: "view",
    inputs: [
      { name: "agentId", type: "uint256" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [
      { name: "authorized", type: "bool" },
      { name: "reason", type: "string" },
    ],
  },
  {
    type: "function",
    name: "emergencyFreeze",
    stateMutability: "nonpayable",
    inputs: [{ name: "agentId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "appealAndUnfreeze",
    stateMutability: "nonpayable",
    inputs: [
      { name: "agentId", type: "uint256" },
      { name: "newCap", type: "uint256" },
    ],
    outputs: [],
  },
  { type: "error", name: "AgentPaused", inputs: [] },
  { type: "error", name: "AgentNotPaused", inputs: [] },
  { type: "error", name: "NotAuthorized", inputs: [] },
  { type: "error", name: "InvalidCap", inputs: [] },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address" }],
  },
] as const;
